### ISSUE TITLE
ponies puke on commit

### ISSUE THREAD

**Issue by ke4qqq** [iliana/mw#1]
Let me start by saying "First Post"

Grabbed User:ke4qqq from fp.o mw. Made a small 7 char substitution tried mw commit and received: 

You have mail in /var/spool/mail/ke4qqq
[ke4qqq@nalleyx60 mw]$ bin/mw init https://fedoraproject.org/w/api.php
[ke4qqq@nalleyx60 mw]$ bin/mw login
Username: ke4qqq
Password: 
Login successful! (yay)
[ke4qqq@nalleyx60 mw]$ bin/mw pull User:Ke4qqq
[ke4qqq@nalleyx60 mw]$ vim User:Ke4qqq.wiki 
[ke4qqq@nalleyx60 mw]$ bin/mw commit User:Ke4qqq
WARNING: mw does not do collision detection yet.
Hit ^C now if you haven't double checked, otherwise hit Enter

U User:Ke4qqq.wiki
Edit summary: changing city
Traceback (most recent call last):
  File "bin/mw", line 23, in <module>
    ponies.main()
  File "/home/ke4qqq/mwcommit/mw/src/mw/cli.py", line 73, in main
    self.all_commands[the_command].main()
  File "/home/ke4qqq/mwcommit/mw/src/mw/clicommands.py", line 51, in main
    self._do_command()
  File "/home/ke4qqq/mwcommit/mw/src/mw/clicommands.py", line 227, in _do_command
    md5.update(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)
[ke4qqq@nalleyx60 mw]$ bin/mw login
Username: ke4qqq
Password: 
Login successful! (yay)
[ke4qqq@nalleyx60 mw]$ bin/mw commit User:Ke4qqq
WARNING: mw does not do collision detection yet.
Hit ^C now if you haven't double checked, otherwise hit Enter

U User:Ke4qqq.wiki
Edit summary: changing city
Traceback (most recent call last):
  File "bin/mw", line 23, in <module>
    ponies.main()
  File "/home/ke4qqq/mwcommit/mw/src/mw/cli.py", line 73, in main
    self.all_commands[the_command].main()
  File "/home/ke4qqq/mwcommit/mw/src/mw/clicommands.py", line 51, in main
    self._do_command()
  File "/home/ke4qqq/mwcommit/mw/src/mw/clicommands.py", line 227, in _do_command
    md5.update(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)

**Comment by iliana** [comment]
Should be fixed in 0975deb337c03e986718bf2cbbb54377e2e67882

**Comment by ke4qqq** [comment]
this appears fixed - thanks
