### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by theiceman** [iliana/mw#11]
```$ mw login  
Username: username
Password: 
Traceback (most recent call last):
  File "/usr/bin/mw", line 23, in <module>
    ponies.main()
  File "/usr/lib/python2.7/site-packages/mw/cli.py", line 73, in main
    self.all_commands[the_command].main()
  File "/usr/lib/python2.7/site-packages/mw/clicommands.py", line 49, in main
    self._do_command()
  File "/usr/lib/python2.7/site-packages/mw/clicommands.py", line 110, in _do_command
    self._login()
  File "/usr/lib/python2.7/site-packages/mw/clicommands.py", line 59, in _login
    'lgpassword': passwd})
  File "/usr/lib/python2.7/site-packages/simplemediawiki.py", line 148, in call
    return json.loads(self._fetch_http(self._api_url, params))
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 385, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 402, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 420, in raw_decode
    raise JSONDecodeError("No JSON object could be decoded", s, idx)
simplejson.decoder.JSONDecodeError: No JSON object could be decoded: line 1 column 0 (char 0)

```
```

**Comment by iliana** [comment]
This isn't extremely helpful. What was the full `mw init` command you used?

**Comment by theiceman** [comment]
My bad i didn't include the path to api.php in the url,

Thank you.
